
package eRead.ui;

import eRead.db.BookDAO;
import eRead.entity.Book;


public class AddBookDlg extends javax.swing.JDialog {

    /**
     * Creates new form AddBookDlg
     */
    public AddBookDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    AddBookDlg() {
        initComponents();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tBookName = new javax.swing.JTextField();
        tAuthor = new javax.swing.JTextField();
        tBookId = new javax.swing.JTextField();
        tStock = new javax.swing.JTextField();
        bSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add Book");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 30, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Book Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 140, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Author :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 190, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Book Id :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 240, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Stock :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 290, 60, 17);
        getContentPane().add(tBookName);
        tBookName.setBounds(260, 150, 200, 30);
        getContentPane().add(tAuthor);
        tAuthor.setBounds(260, 190, 200, 30);
        getContentPane().add(tBookId);
        tBookId.setBounds(260, 230, 200, 30);
        getContentPane().add(tStock);
        tStock.setBounds(260, 270, 200, 30);

        bSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bSubmit.setText("Add Book");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(bSubmit);
        bSubmit.setBounds(260, 320, 110, 30);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 240, 0, 0);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 330, 0, 0);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 290, 270, 90);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(369, 100, 80, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eRead/ui/addb.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 80, 474, 320);

        setSize(new java.awt.Dimension(488, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        // TODO add your handling code here:
          try
        {
            String bookName, author ,bookId ,stock,status;
            bookName = tBookName.getText();
            author = tAuthor.getText();
            bookId = tBookId.getText();
            stock = tStock.getText();
            status = "Available";
            String s = BookDAO.checkStock(bookId);
            if((bookId.indexOf(" ") != -1) || bookId.length()== 0)
            {
               javax.swing.JOptionPane.showMessageDialog(this, "Book Id invalid"); 
            }
            else if( bookName.length()== 0)
            {
               javax.swing.JOptionPane.showMessageDialog(this, "Book Name is invalid"); 
            }
            else if( author.length()== 0)
            {
               javax.swing.JOptionPane.showMessageDialog(this, "Author Name is invalid"); 
            }
            else if( Integer.parseInt(stock) < 0)
            {
               javax.swing.JOptionPane.showMessageDialog(this, "Invalid stock"); 
            }
            
            else
            {
            
            
                int newStock = Integer.parseInt(s) + Integer.parseInt(stock);
                if(Integer.parseInt(s) >= 0)
                {
                    BookDAO.updateBook(bookId , Integer.toString(newStock));
                    BookDAO .updateStatus(bookId ,"Available");
                    javax.swing.JOptionPane.showMessageDialog(this, "Book Added");
                }
                else
                {
                    Book bk = new Book();
                    bk.setBookId(bookId);
                    bk.setAuthor(author );
                    bk.setBookName(bookName);
                    bk.setStock(stock);
                    bk.setStatus(status);
                    System.out.println("1");
                    BookDAO u = new BookDAO();
                    System.out.println("2");
                    u.insert(bk);
                    System.out.println("3");
                    javax.swing.JOptionPane.showMessageDialog(this, "Book Added");
                    tBookName.setText("");
                    tAuthor.setText("");
                    tBookId.setText("");
                    tStock.setText("");
                }
            }
            
           
        }
        catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(this, "Invalid stock Input");
           tBookName.setText("");
            tAuthor.setText("");
            tBookId.setText("");
            tStock.setText("");
        }
        
    }//GEN-LAST:event_bSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LibrarianDlg dl = new LibrarianDlg();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBookDlg dialog = new AddBookDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tAuthor;
    private javax.swing.JTextField tBookId;
    private javax.swing.JTextField tBookName;
    private javax.swing.JTextField tStock;
    // End of variables declaration//GEN-END:variables
}
