/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eRead.ui;


public class AdminDlg extends javax.swing.JDialog {

    /**
     * Creates new form AdminDlg
     */
    public AdminDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    AdminDlg() {
        initComponents();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bAddLibrarian = new javax.swing.JButton();
        bRemoveLibrarian = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Admin");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 10, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 50);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);

        bAddLibrarian.setText("ADD LIBRARIAN");
        bAddLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddLibrarianActionPerformed(evt);
            }
        });
        jPanel2.add(bAddLibrarian);
        bAddLibrarian.setBounds(170, 120, 190, 30);

        bRemoveLibrarian.setBackground(new java.awt.Color(204, 204, 204));
        bRemoveLibrarian.setText("REMOVE LIBRARIAN");
        bRemoveLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveLibrarianActionPerformed(evt);
            }
        });
        jPanel2.add(bRemoveLibrarian);
        bRemoveLibrarian.setBounds(170, 220, 190, 30);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(420, 310, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eRead/ui/adminpic_1.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 660, 540);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 640, 560);

        setSize(new java.awt.Dimension(550, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddLibrarianActionPerformed
        // TODO add your handling code here:
        UserDetailsDlg usr = new UserDetailsDlg();
        usr.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_bAddLibrarianActionPerformed

    private void bRemoveLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveLibrarianActionPerformed
        // TODO add your handling code here:
        RemoveLibrarianDlg reLib = new RemoveLibrarianDlg();
        reLib.setVisible(true);
        this.dispose();
         
        
    }//GEN-LAST:event_bRemoveLibrarianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminDlg dialog = new AdminDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddLibrarian;
    private javax.swing.JButton bRemoveLibrarian;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
