
package eRead.ui;

import eRead.db.UserDAO;
import eRead.entity.User;


public class LoginDlg extends javax.swing.JDialog {

    /**
     * Creates new form LoginDlg
     */
    public LoginDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    LoginDlg() {
        initComponents();
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tUserId = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        bSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                               Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 320, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 70);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("User Id :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 100, 70, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Password : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 150, 90, 30);
        jPanel2.add(tUserId);
        tUserId.setBounds(240, 90, 140, 30);
        jPanel2.add(tPassword);
        tPassword.setBounds(240, 150, 140, 30);

        bSubmit.setText("Login");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(bSubmit);
        bSubmit.setBounds(270, 200, 110, 23);

        jButton1.setText("Cancel ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(133, 200, 80, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eRead/ui/loginpic.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(4, 4, 470, 310);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 510, 310);

        setSize(new java.awt.Dimension(486, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed

        // TODO add your handling code here:
        String UserId , password;
        UserId = tUserId.getText();
        password = String.valueOf(tPassword.getPassword());
        try
        {
            
            User useOne = new User();
            useOne = UserDAO.readOne(UserId);
            String userPassword = useOne.getPassword();
         if(userPassword.equals(password))
         {
              String role = useOne.getRole();
              if("Student".equalsIgnoreCase(role))
              {
                  StudentDlg stu = new StudentDlg(UserId);
                  stu.setVisible(true);
                  
                  this.dispose();
              }
              else if("Librarian".equalsIgnoreCase(role))
              {
                   
                  LibrarianDlg lib = new LibrarianDlg();
                  lib.setVisible(true);
                  this.dispose();
                
              }
              
              else if("Admin".equalsIgnoreCase(role))
              {
                  AdminDlg adm = new AdminDlg();
                  adm.setVisible(true);
                  this.dispose();
              }
              else
             {
                  javax.swing.JOptionPane.showMessageDialog(this,"User Id or Password incorrect");
             }
             
              
          }
         else
         {
             javax.swing.JOptionPane.showMessageDialog(this,"User Id or Password incorrect"); 
         }
    
        } 
           
        catch(Exception ex)
        {
            
            javax.swing.JOptionPane.showMessageDialog(this, "user id or password incorrect");
        }
        
        
    }//GEN-LAST:event_bSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDlg dialog = new LoginDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUserId;
    // End of variables declaration//GEN-END:variables
}
