
package eRead.ui;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import eRead.db.UserDAO;
import static eRead.db.UserDAO.deleteLibrarian;
import eRead.entity.User;


public class RemoveLibrarianDlg extends javax.swing.JDialog {

    /**
     * Creates new form RemoveLibrarianDlg
     */
    public RemoveLibrarianDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            List<User> uslist = new ArrayList<>();
            uslist = UserDAO.readLibrarian();
            for (User usr : uslist) {
                cbLibrarianList.addItem(usr.getUserId() + " - " + usr.getName());
            }
        } catch (Exception ex) {
            //ex.printStackTrace();
        }
    }

    RemoveLibrarianDlg() {
        initComponents();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try {
            List<User> uslist = new ArrayList<>();
            uslist = UserDAO.readLibrarian();
            for (User usr : uslist) {
                cbLibrarianList.addItem(usr.getUserId() + " - " + usr.getName());
            }
        } catch (Exception ex) {
            //ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbLibrarianList = new javax.swing.JComboBox();
        bRemove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("Remove Librarian");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 40, 110, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 0);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        cbLibrarianList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLibrarianListActionPerformed(evt);
            }
        });
        jPanel2.add(cbLibrarianList);
        cbLibrarianList.setBounds(150, 230, 230, 30);

        bRemove.setText("Remove librarian");
        bRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(bRemove);
        bRemove.setBounds(190, 280, 150, 30);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(379, 120, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Remove Librarian");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 40, 200, 30);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(400, 360, 0, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eRead/ui/removel.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 80, 500, 340);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 450);

        setSize(new java.awt.Dimension(514, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveActionPerformed
        // TODO add your handling code here:
        String librarian = (String) cbLibrarianList.getSelectedItem();
        String[] userId = librarian.split("-");
        
        UserDAO.deleteLibrarian(userId[0].trim());
        cbLibrarianList.removeItem(librarian);
        javax.swing.JOptionPane.showMessageDialog(this, "Librarian removed");
        

    }//GEN-LAST:event_bRemoveActionPerformed

    private void cbLibrarianListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLibrarianListActionPerformed
        // TODO add your handling code here:
//        try {
//
//            List<User> uslist = new ArrayList<>();
//            uslist = UserDAO.readLibrarian();
//            for (int i = 0; i < uslist.size(); i++) {
//                String uId = uslist.get(i).getUserId();
//                String name = uslist.get(i).getName();
//                System.out.println(uId + name);
//                cbLibrarianList.addItem(uId.concat(" " + name));
//            }
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }

    }//GEN-LAST:event_cbLibrarianListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminDlg admin = new AdminDlg();
        admin.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveLibrarianDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveLibrarianDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveLibrarianDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveLibrarianDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RemoveLibrarianDlg dialog = new RemoveLibrarianDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRemove;
    private javax.swing.JComboBox cbLibrarianList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
