
package eRead.ui;

import eRead.db.UserDAO;
import eRead.entity.User;


public class UserDetailsDlg extends javax.swing.JDialog {

    /**
     * Creates new form UserDetails1
     */
    public UserDetailsDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    UserDetailsDlg() {
         initComponents();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tUId = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        bRegister = new javax.swing.JButton();
        tPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User Id  :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 70, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 130, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 180, 60, 20);
        jPanel2.add(tUId);
        tUId.setBounds(320, 70, 150, 30);

        tName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameActionPerformed(evt);
            }
        });
        jPanel2.add(tName);
        tName.setBounds(320, 170, 150, 30);

        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(bRegister);
        bRegister.setBounds(330, 250, 110, 30);
        jPanel2.add(tPassword);
        tPassword.setBounds(320, 120, 150, 30);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(460, 170, 0, 0);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(460, 20, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eRead/ui/userpic_1.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 626, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 630, 430);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ADD LIBRARIAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 10, 270, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 60);

        setSize(new java.awt.Dimension(642, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameActionPerformed

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        // TODO add your handling code here:
           try
        {
            String userId,password,role,name;
            userId = tUId.getText();
            password = String.valueOf(tPassword.getPassword());
            name= tName.getText();
            role= "Librarian";
            if((userId.indexOf(" ") != -1) || userId.length()== 0 )
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Librarian id");
                
            }
            else if((password.indexOf(" ") != -1) || password.length()== 0  )
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid password");
                
            }
            else
            {    
                User userdetails = new User(); 
                userdetails.setUserId(userId);
                userdetails.setPassword(password );
                userdetails.setName(name);
                userdetails.setRole(role);
                UserDAO u = new UserDAO();
                u.insert(userdetails);
                javax.swing.JOptionPane.showMessageDialog(this, "Librarian registered");
                tUId.setText("");
                tName.setText("");
                tPassword.setText("");
            }
            
            
            
        }
        catch(Exception e)
        {
          javax.swing.JOptionPane.showMessageDialog(this, "User id alreay exists"); 
          tUId.setText("");
          tName.setText("");
          tPassword.setText("");
        }
           
        
            
    }//GEN-LAST:event_bRegisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       AdminDlg admin = new AdminDlg();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetailsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetailsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetailsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetailsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserDetailsDlg dialog = new UserDetailsDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegister;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tName;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUId;
    // End of variables declaration//GEN-END:variables
}
